### ISSUE TITLE
AssertionError when getting values in quick succession

### ISSUE THREAD

**Issue by jamesd-uk** [drewarnett/pypicoboard#1]
I'm sure this is an issue with my code, but I'm out of ideas. Here's what I'm using:

```
from picoboard import PicoBoard
pb = PicoBoard('/dev/ttyUSB1')    # or 'COM1' or '/dev/ttyS0', etc.

while True:
            readings = pb.read()
            print(readings["slider"])
```

I get this error. Sometimes it is immediate after the loop begins, other times, the loop can iterate over 1000 times.

```
Traceback (most recent call last):
  File "test2.py", line 7, in <module>
    readings = pb.read()
  File "/home/pi/pypicoboard/picoboard.py", line 101, in read
    channel, value = readchannel()
  File "/home/pi/pypicoboard/picoboard.py", line 87, in readchannel
    assert (upper_byte >> 7) & 1 == 1
AssertionError
```

This still occurs when waiting for 0.5 seconds before reading again, in case I was pushing too fast. This also occurs with all inputs. It's seemingly random. It doesn't happen after a set amount of iterations.

Any suggestions would be greatly appreciated!

**Comment by drewarnett** [comment]
I looked into this a bit with The-Cheese Eater.

He is using a Sparkfun Picoboard with a USB interface.

I added the values to the assertion statement to be a bit more helpful for trouble shooting.  Then he ran this code:
```
from picoboard import PicoBoard
pb = PicoBoard('/dev/ttyUSB1')

while True:
    readings = pb.read()
    print(readings["light"])
```

Which crashed with output:
```
141
203
 
Traceback (most recent call last):
  File "/home/james/Downloads/test.py", line 5, in <module>
    readings = pb.read()
  File "/home/james/.local/lib/python2.7/site-packages/picoboard.py", line 107, in read
    channel, value = readchannel()
  File "/home/james/.local/lib/python2.7/site-packages/picoboard.py", line 92, in readchannel
    assert (upper_byte >> 7) & 1 == 1, (upper_byte, lower_byte)
AssertionError: (10, 176)
```

I was unable to reproduce the problem.  I am using an OSEPP Uno R3 Plus with firmware from:

     https://learn.sparkfun.com/tutorials/digitalsandbox-picoboard

I ran this program to torture test my picoboard:
```
#! /usr/bin/env python3

import time

from picoboard import PicoBoard
pb = PicoBoard('/dev/ttyUSB0')

count = 0
start = time.time()
try:
    while True:
        readings = pb.read()
        count += 1
except KeyboardInterrupt:
    end = time.time()
    print("Transactions:  {}".format(count))
    print("Transaction rate (transactions/s):  {}".format(count/(end - start)))
except Exception as e:
    end = time.time()
    print("Transactions:  {}".format(count))
    print("Transaction rate (transactions/s):  {}".format(count/(end - start)))
    raise e
```
I ran it for quite a while without crashing.  I CONTROL-C'ed out of it and got:
```
Transactions:  199942
Transaction rate (transactions/s):  62.55396817263315

```
The only thing further I could do to trouble shoot would be to refactor the code to read the entire message, then parse it, and if it fails, to report the entire message.  This also hints at a possible ruggedizing that could be done.  If we don't trust the micro to send a complete well formed message, if it fails to parse, discard it and just continue on.

It might be interesting to read through the source code for the official picoboard.  It appears to be here:

     https://github.com/sparkfun/PicoBoard

I will leave this ticket open, but will tag it as needing help with reproducing.
